config/routes.rb
Rails.application.routes.draw do

  resources :book_lessons
  resources :lessons2s
  resources :lessons1s
devise_for :users, :controllers => {  registrations: 'users/registrations',  omniauth_callbacks: 'users/omniauth_callbacks'}

  resources :lessons
  #devise_for :users
  resources :courses
 
  root "home#index"
  get 'home/activity'




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index,:edit,:show,:update]

# get '/provider/callback', to: 'sessions#create'
# get '/logout', to: 'sessions#destroy', as: 'logout'
#   # get '/logout', to: 'sessions#destroy', as: 'logout'
end

app/models/lesson.rb
class Lesson < ApplicationRecord
	validates :title, presence:true
	validates  :lname,presence:true
	 include RankedModel
     ranks :row_order
     Lesson.rank(:row_order).all

     # def previous_post
    # 	@lessons.where("row_order < ?", row_order).order(:row_order).last
     # end
  #      def prev
  #   @lesson.where("row_order < ?", row_order).order(:row_order).last
  # end
  def previous_post
  # self.class.first(:conditions => ["title < ?", title], :order => "title desc")
  self.class.where("row_order < ?", row_order).order(:row_order).last
end

 def next_post
  # self.class.first(:conditions => ["title < ?", title], :order => "title desc")
  self.class.where("row_order < ?", row_order).order(:row_order).first
end
     # def prev
     #   @lesson.where("row_order < ?", row_order).order(:row_order).last

     # end
     # def next
     # 	lessons.where("row_order > ?", row_order).order(:row_order)

     # end
                       
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show edit update destroy ]

  # GET /lessons or /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1 or /lessons/1.json
  def show
    Lesson.rank(:row_order).all
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to lesson_url(@lesson), notice: "Lesson was successfully created." }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to lesson_url(@lesson), notice: "Lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to lessons_url, notice: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:lname, :title)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@lesson) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :lname
    = f.input :title
    = f.rich_text_area :title

  .form-actions
    = f.button :submit

app/views/lessons/edit.html.haml
%h1 Editing lesson

= render 'form'

= link_to 'Show', @lesson
\|
= link_to 'Back', lessons_path

app/views/lessons/index.html.haml
%h1 Listing lessons

%table.table
  %thead
    %tr
      %th Lname
      %th Title
      %th ranking
      %th order by

      %th
      %th
      %th

  %tbody
    - @lessons.each do |lesson|
      %tr
        %td= lesson.lname
        %td= lesson.title
        %td= lesson.row_order
        %td= lesson.row_order_rank+1
        %td= link_to 'Show', lesson,class:'btn btn-warning  '
        %td= link_to 'Edit', edit_lesson_path(lesson),class:'btn btn-success'
        %td= link_to 'Destroy', lesson, method: :delete,class:'btn btn-primary', data: { confirm: 'Are you sure?' }

%br
  %ul#sortable
    %li.ui-state-default
      %span.ui-icon.ui-icon-arrowthick-2-n-s>
      Item 1
    %li.ui-state-default
      %span.ui-icon.ui-icon-arrowthick-2-n-s>
      Item 2
    %li.ui-state-default
      %span.ui-icon.ui-icon-arrowthick-2-n-s>
      Item 3
    %li.ui-state-default
      %span.ui-icon.ui-icon-arrowthick-2-n-s>
      Item 4
    %li.ui-state-default
      %span.ui-icon.ui-icon-arrowthick-2-n-s>
      Item 5
    %li.ui-state-default
      %span.ui-icon.ui-icon-arrowthick-2-n-s>
      Item 6
    %li.ui-state-default
      %span.ui-icon.ui-icon-arrowthick-2-n-s>
      Item 7


/ =@lessons.row_order
= link_to 'New Lesson', new_lesson_path,class:'btn btn-success text-center'

app/views/lessons/new.html.haml
%h1 New lesson

= render 'form'

= link_to 'Back', lessons_path

app/views/lessons/show.html.haml
%p#notice= notice

%p
  %b Lname:
  = @lesson.lname
%p
  %b Title:
  = @lesson.title


= link_to 'Edit', edit_lesson_path(@lesson)
\|
= link_to 'Back', lessons_path
/ = link_to("Previous Post", @lesson.prev) if @lesson.prev
= link_to("<", @lesson.previous_post) if @lesson.previous_post 
= link_to("Next Post", @lesson.next_post) if @lesson.next_post 

/ - unless @lesson.prev.nil?
/   = link_to 'pre',lessons_path(@lesson.prev)