config/routes.rb
Rails.application.routes.draw do

  resources :book_lessons
  resources :lessons2s
  resources :lessons1s
devise_for :users, :controllers => {  registrations: 'users/registrations',  omniauth_callbacks: 'users/omniauth_callbacks'}

  resources :lessons
  #devise_for :users
  resources :courses
 
  root "home#index"
  get 'home/activity'




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index,:edit,:show,:update]

# get '/provider/callback', to: 'sessions#create'
# get '/logout', to: 'sessions#destroy', as: 'logout'
#   # get '/logout', to: 'sessions#destroy', as: 'logout'
end

app/models/book_lesson.rb
class BookLesson < ApplicationRecord
  belongs_to :course
   extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/book_lessons_controller.rb
class BookLessonsController < ApplicationController
  before_action :set_book_lesson, only: %i[ show edit update destroy ]

  # GET /book_lessons or /book_lessons.json
  def index
    @book_lessons = BookLesson.all
  end

  # GET /book_lessons/1 or /book_lessons/1.json
  def show
  end

  # GET /book_lessons/new
  def new
    @book_lesson = BookLesson.new
  end

  # GET /book_lessons/1/edit
  def edit
  end

  # POST /book_lessons or /book_lessons.json
  def create
    @book_lesson = BookLesson.new(book_lesson_params)

    respond_to do |format|
      if @book_lesson.save
        format.html { redirect_to book_lesson_url(@book_lesson), notice: "Book lesson was successfully created." }
        format.json { render :show, status: :created, location: @book_lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book_lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_lessons/1 or /book_lessons/1.json
  def update
    respond_to do |format|
      if @book_lesson.update(book_lesson_params)
        format.html { redirect_to book_lesson_url(@book_lesson), notice: "Book lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @book_lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book_lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_lessons/1 or /book_lessons/1.json
  def destroy
    @book_lesson.destroy

    respond_to do |format|
      format.html { redirect_to book_lessons_url, notice: "Book lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_lesson
      @book_lesson = BookLesson.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_lesson_params
      params.require(:book_lesson).permit(:title, :content, :course_id)
    end
end

app/helpers/book_lessons_helper.rb
module BookLessonsHelper
end

app/views/book_lessons/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@book_lesson) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :content
    = f.association :course

  .form-actions
    = f.button :submit

app/views/book_lessons/edit.html.haml
%h1 Editing book_lesson

= render 'form'

= link_to 'Show', @book_lesson
\|
= link_to 'Back', book_lessons_path

app/views/book_lessons/index.html.haml
%h1 Listing book_lessons

%table
  %thead
    %tr
      %th Title
      %th Content
      %th Course
      %th
      %th
      %th

  %tbody
    - @book_lessons.each do |book_lesson|
      %tr
        %td= book_lesson.title
        %td= book_lesson.content
        %td= book_lesson.course
        %td= link_to 'Show', book_lesson
        %td= link_to 'Edit', edit_book_lesson_path(book_lesson)
        %td= link_to 'Destroy', book_lesson, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Book lesson', new_book_lesson_path

app/views/book_lessons/new.html.haml
%h1 New book_lesson

= render 'form'

= link_to 'Back', book_lessons_path

app/views/book_lessons/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @book_lesson.title
%p
  %b Content:
  = @book_lesson.content
%p
  %b Course:
  = @book_lesson.course

= link_to 'Edit', edit_book_lesson_path(@book_lesson)
\|
= link_to 'Back', book_lessons_path